allowBuilds:
  "@tsparticles/engine": true
  esbuild: true
  fallow: true
  msw: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - payload-doctor
  - react-doctor
  - "@tsparticles/*"
  - "@better-auth/*"
  - better-auth
